version: '3'
services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/fampay_youtube_assignment
    ports:
      - 8000:8000
    links:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
